### ISSUE TITLE
Incorrect bitcode support in supplied binaries

### ISSUE THREAD

**Issue by defagos** [TagCommander/pods#1]
If you archive a project containing the TagCommander binaries (bitcode version), archiving fails with the following error (here for the arm64 architecture):

`
ld: bitcode bundle could not be generated because '/path/to/framework/TCCore.framework/TCCore' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build for architecture arm64
`

The problem probably affects all other TagCommander SDKs.

## How to reproduce

Try to archive any project containing the bitcode version of the TagCommander SDK.

If you don't have one, you can create one very easily:

1. Create a new Xcode project for a single view project (which has bitcode enabled by default).
1. Download the [current bitcode release binaries](https://github.com/TagCommander/pods/raw/7d003dad98a83b60f0ff4d4e2f77f42eb6f23fd3/TCCore/Release-universal/4.1.2-Bitcode.zip) for TCCore.
1. Add the binaries to the Xcode embedded frameworks for the target.
1. Setup automatic code signing settings properly and archive the project. The build will fail with the above error.

## How to fix

To fix this issue, the frameworks must be properly generated using Xcode its archive command, as suggested by the error message above.

1. Generate the framework again.
1. Replace the framework binaries from your test project with the new ones.
1. Archive the project again. Compilation should work just fine.
1. Repeat the process for all other SDKs to ensure that all are correctly enabled for bitcode.

**Comment by CommandersAct** [comment]
Thanks a lot for this. Never realised it wasn't working when you'd try to archive the application while it was not an issue when compiling...

I modified my scripts to be able to compile with Archive all bitcode versions.
This can't be done for simulator so I removed at the same time the universal versions for bitcode.

Please tell me if it's seems ok for you !

**Comment by defagos** [comment]
The binaries do not work since you removed bitcode entirely from your universal build. What we need is a universal binary (containing all device and simulator slices) enabled for bitcode.

I don't have access to your build scripts, but the idea is probably a minor adjustment to what you are already doing: 

* Build the framework for simulator and device SDKs separately, enabling bitcode form device binaries.
* Use the `lipo` command to join the binaries into a universal SDK.

I described below how this can be made from the command line. I assume the commands are run from the main project directory (containing your `xcodeproj` project or workspace), and that you have a `TCCore` framework scheme with a Release configuration. The same can be done for other framework schemes and other build flavors (e.g. Debug) to produce all universal frameworks:

```
xcodebuild -scheme TCCore -sdk iphonesimulator -configuration Release ONLY_ACTIVE_ARCH=NO
xcodebuild -scheme TCCore -sdk iphoneos -configuration Release BITCODE_GENERATION_MODE=bitcode
cp -R build/Release-iphoneos build/Release-universal
xcrun lipo -create build/Release-iphoneos/TCCore.framework/TCCore build/Release-iphonesimulator/TCCore.framework/TCCore -output build/Release-universal/TCCore.framework/TCCore
```

The first two commands build two frameworks for the simulator and device respectively, saving the results in separate folders under `./build`. The device framework is then copied to a universal folder, and the final `lipo` command merges the simulator and device binaries, saving the result as main universal binary. This universal framework can be then added to a project and will archive fine.

Thanks for your help!

**Comment by CommandersAct** [comment]
Should be working now :)

**Comment by defagos** [comment]
Thank you very much for your help, everything now works perfectly.

**Comment by MrCloud** [comment]
@defagos @TagCommander Is this issue appearing again ? Using version 4.2.3 seems to reproduce the same issue: 
`.../Pods/latest-TCCore-Release-universal/TCCore.framework/TCCore' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target.`

**Comment by CommandersAct** [comment]
@MrCloud You're right, I'm gonna check why a create a new version asap.

Thank you for the feedback.

**Comment by CommandersAct** [comment]
@MrCloud in fact, you're using the regular TCCore which doesn't have bitcode enabled. You should use https://github.com/TagCommander/pods/raw/master/TCCore/Release-universal/4.2.3-Bitcode.zip which has bitcode for armv7 and arm64.
