### ISSUE TITLE
Cannot find -noIDFA-noIAB pod version compatible with Xcode 12 simulators

### ISSUE THREAD

**Issue by gudavo** [TagCommander/pods#11]
Hello,

I need to use -noIDFA-noIAB versions of TCCore and TCPrivacy libs to meet business requirements.

First, there is no Debug-universal-noIDFA-noIAB version of these libs, only Release-universal-Bitcode-noIDFA-noIAB.

Second, latest versions of these libs do not include -noIDFA-noIAB , for example: https://github.com/TagCommander/pods/tree/master/TCCore/4/7/2

It seems TCCore 4.6.8 and TCPrivacy 4.6.9 are the latest versions with -noIDFA-noIAB, but they produce the following error when trying to run with Xcode 12.2 on iOS 14.2 simulator:
> Could not find module 'TCPrivacy' for target 'x86_64-apple-ios-simulator'; found: arm64, armv7-apple-ios, arm64-apple-ios, arm, armv7

So can you provide Debug and Release -noIDFA-noIAB versions compatible with Xcode 12.2 iOS 14.2 simulator ?

Thanks

**Comment by gudavo** [comment]
Also it seems your  podspec for latest-TCPrivacy-Release-Bitcode-noIDFA-noIAB (https://raw.githubusercontent.com/TagCommander/pods/master/TCPrivacy/latest-TCPrivacy-Release-Bitcode-noIDFA-noIAB.podspec) points to a missing zip file:
https://github.com/TagCommander/pods/raw/master/TCPrivacy/4/6/5/Release/TCPrivacy-Bitcode-noIDFA-noIAB.zip returns a 404 error

**Comment by CommandersAct** [comment]
Hello !
We removed "noIAB" versions of binaries beside the ones for TCPrivacy because it only affects TCPrivacy.
You can use TCCore-Debug-noIDFA.podspec for TCCore.

But you're are right we are missing -noIDFA-noIAB for the debug version of TCPrivacy.
I will publish a new release on monday, I'll check to be sure that we add this version with it. Meanwhile if you're using Bitcode, please use TCPrivacy-Release-Bitcode-noIDFA-noIAB.podspec.

p.s. our latest are for XCode11 and before for now :(

**Comment by gudavo** [comment]
Thanks for your answer.
What do you mean "our latest are for XCode11 and before for now"? Which versions are compatible with Xcode12?

**Comment by CommandersAct** [comment]
the podspec named latest-somthing are for XCode 11.
The latest "versions" of the frameworks are for XCode 12.

For TCPrivacy and TCCore those are 4.7.x

**Comment by gudavo** [comment]
OK I see, so when the new TCPrivacy-Debug-noIDFA-noIAB is released, I will have something like this in my Podfile:

``` ruby
  pod 'TCCore-Debug-noIDFA', :podspec => 'https://raw.githubusercontent.com/TagCommander/pods/master/TCCore/4/7/2/TCCore-Debug-noIDFA.podspec', :configuration => ['Debug']
  pod 'TCPrivacy-Debug-noIDFA-noIAB', :podspec => 'https://raw.githubusercontent.com/TagCommander/pods/master/TCPrivacy/4/7/5/TCPrivacy-Debug-noIDFA-noIAB.podspec', :configuration => ['Debug']
  
  pod 'TCCore-Release-Bitcode-noIDFA', :podspec => 'https://raw.githubusercontent.com/TagCommander/pods/master/TCCore/4/7/2/TCCore-Release-Bitcode-noIDFA.podspec', :configuration => ['Release']
  pod 'TCPrivacy-Release-Bitcode-noIDFA-noIAB', :podspec => 'https://raw.githubusercontent.com/TagCommander/pods/master/TCPrivacy/4/7/5/TCPrivacy-Release-Bitcode-noIDFA-noIAB.podspec', :configuration => ['Release']
```

Right?

**Comment by CommandersAct** [comment]
Yes !

**Comment by gudavo** [comment]
The `configuration(s)` parameter does not work with the latest `.xcframework` libs, the above configuration produces a build error:

> error: Multiple commands produce '/Users/gdavo/Library/Developer/Xcode/DerivedData/ParionsSport-ecwczspqicrjjncelblqzyooapvf/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/TCPrivacy':
> 1) That command depends on command in Target 'TCPrivacy-Debug-noIDFA-noIAB' (project 'Pods'): script phase “[CP] Copy XCFrameworks”
> 2) That command depends on command in Target 'TCPrivacy-Release-Bitcode-noIDFA-noIAB' (project 'Pods'): script phase “[CP] Copy XCFrameworks”

**Comment by CommandersAct** [comment]
Did you take the one released 30 minutes ago?
I changed nothing in the release scripts neither did I change anything in the plists, do you have any idea of what could cause this? I saw on internet "If you use CocoaPods you may want to try deintegrate the pods and install again. It works for me." Did you try this already?
If I find what's happening I'll create a new release.

**Comment by gudavo** [comment]
Hello,
Yes I took the new TCPrivacy 4.7.5 version released yesterday.
It seems the issue is related to the migration to XCFramework, you cannot use `:configuration` parameter anymore.

See https://github.com/CocoaPods/CocoaPods/issues/10106

**Comment by CommandersAct** [comment]
I was just looking at the same post :D Was trying to figure if I could do something or not.

**Comment by gudavo** [comment]
Well you could provide a single XCframework per library instead of having separated Debug / Release versions.

One advantage of XCframework is that you can distribute binary libraries for multiple platforms and architectures in a single bundle. Thus you do no longer need to merge (lipo) multiple architectures into a single binary, only to later have to remove the Simulator slice during the archive phase. (source: https://pspdfkit.com/blog/2020/supporting-xcframeworks/)

**Comment by CommandersAct** [comment]
Hello !
I created a new release for each modules with a single XCFramework per library containing the dsyms inside.
And forgotten variants were also added.

**Comment by gudavo** [comment]
Thanks, it solves the configuration problem.
