### ISSUE TITLE
Add target x86_64-apple-ios-simulator into your Debug version

### ISSUE THREAD

**Issue by tonicfx** [TagCommander/pods#12]
Hello, the only solution to launch TagCommander into iOS Simulator is to use Bitcode version of your SDKs.

Is it possible to include x86_64-apple-ios-simulator into your 'latest-XXXX-Debug-universal' library to be able to launch application into iOS Simulator ?

Thanks for your help.

**Comment by CommandersAct** [comment]
Hello !
I'm not sure I'm following you. I tried using lipo:

% lipo -info /Users/JJ/Sources/github-pods/TCCore/4/6/8/Debug-universal/TCCore/TCCore.framework/TCCore
Architectures in the fat file: /Users/JJ/Sources/github-pods/TCCore/4/6/8/Debug-universal/TCCore/TCCore.framework/TCCore are: x86_64 i386 armv7 arm64 

% lipo -info /Users/JJ/Sources/github-pods/TCSDK/4/5/6/Debug-universal/TCSDK/TCSDK.framework/TCSDK  
Architectures in the fat file: /Users/JJ/Sources/github-pods/TCSDK/4/5/6/Debug-universal/TCSDK/TCSDK.framework/TCSDK are: i386 x86_64 armv7 arm64 

% lipo -info /Users/JJ/Sources/github-pods/TCPrivacy/4/6/15/Debug-universal/TCPrivacy/TCPrivacy.framework/TCPrivacy
Architectures in the fat file: /Users/JJ/Sources/github-pods/TCPrivacy/4/6/15/Debug-universal/TCPrivacy/TCPrivacy.framework/TCPrivacy are: x86_64 i386 armv7 arm64 

All of them have x86_64 inside. Which version of XCode are you using? If you migrated to XCode 12, we recommand using the new pod for XCode 12+ (which sadly don't have a latest for now)

TCCore/4/7/3/TCCore.podspec
TCSDK/4/6/3/TCSDK.podspec
TCPrivacy/4/7/10/TCPrivacy.podspec

They are using xcframeworks so they contain both ios and simulateur as well as release and debug. You might need to update cocoapod to support them tho.

**Comment by tonicfx** [comment]
Hello, thanks for your response.

I have tested lipo too before post, the output is "x86_64 i386 armv7 arm64 ".

However, when I compile my project with target simulator, I have this error : "
PrivacyViewController.swift:10:8: Could not find module 'TCPrivacy' for target 'x86_64-apple-ios-simulator'; found: arm64, armv7-apple-ios, arm64-apple-ios, arm, armv7
"

For information, I have this configuration : pod 1.10.1 / XCode 12.4.

Thanks for your help.

**Comment by tonicfx** [comment]
For information, I have created a XCode project from scratch, with POD setup/init/installe

```
pod 'latest-TCCore-Release-universal', :podspec => 'https://raw.githubusercontent.com/TagCommander/pods/master/TCCore/latest-TCCore-Release-universal.podspec', :configuration => ['Debug','Release']
  pod 'latest-TCSDK-Release-universal', :podspec => 'https://raw.githubusercontent.com/TagCommander/pods/master/TCSDK/latest-TCSDK-Release-universal.podspec', :configuration => ['Debug','Release']
  pod 'latest-TCPrivacy-Release-universal', :podspec => 'https://raw.githubusercontent.com/TagCommander/pods/master/TCPrivacy/latest-TCPrivacy-Release-universal.podspec', :configuration => ['Debug','Release']
```

I just reference Controller with TCPrivacy import : 

```
import Foundation
import TCPrivacy

class PrivacyViewController: TCPrivacyCenterViewController {
    
}
```

I have exactly the same problem, when I run the project into a physical device, it works, when I run the into a simulator, I have this error : 

```
PrivacyViewController.swift:9:8: Could not find module 'TCPrivacy' for target 'x86_64-apple-ios-simulator'; found: arm64, armv7-apple-ios, arm64-apple-ios, arm, armv7
```

My configuration for test : 
XCODE 12.4
COCOAPOD 1.10.1
Target iOS 11 mini
Disable Bitcode for compilation.

Could you test to reproduct error ?

**Comment by CommandersAct** [comment]
Have you tried using the pod specifically for XCode 12?
There is more than often issues when using libraries built with another version of xcode.

If you migrated to XCode 12, we recommand using the new pod for XCode 12+ (which sadly don't have a latest for now)

TCCore/4/7/3/TCCore.podspec
TCSDK/4/6/3/TCSDK.podspec
TCPrivacy/4/7/10/TCPrivacy.podspec

**Comment by tonicfx** [comment]
Hello, thanks for your reply.

It seems to work with these dependancies.

**Comment by CommandersAct** [comment]
Good to hear !
