### ISSUE TITLE
Latest version unavailable

### ISSUE THREAD

**Issue by tonicfx** [TagCommander/pods#15]
Hello, we have error when we try to download latest version 

https://raw.githubusercontent.com/TagCommander/pods/master/TCCore/latest-TCCore-Release-iphoneos.podspec

Error 404 with TCCore / TCSDK and TCPrivacy.

**Comment by CommandersAct** [comment]
Hello !
We reworked our latest releases, all are now using XCFramework. This removes the need of having "Release" and "Debug" version of each module and also removed the need to separate iphoneos and simulators.

You can find all the pods in the base folder of each module like before. 

For example:
https://raw.githubusercontent.com/TagCommander/pods/master/TCCore/latest-TCCore.podspec

**Comment by tonicfx** [comment]
Update your documentation ;)

**Comment by CommandersAct** [comment]
😱  😱  😱  😱  😱  😱  It should have been updated but wasn't  😱  😱  😱  😱  😱  😱

**Comment by tonicfx** [comment]
With the latest Tag Co libs, I have this error at compilation 

❌  /deriveddata/Build/Intermediates.noindex/ArchiveIntermediates/Recette/BuildProductsPath/Recette-iphoneos/TCPrivacy.framework/Modules/TCPrivacy.swiftmodule/arm64.swiftinterface:4:8: no such module 'Swift'

import Swift
^

❌  /modules/privacy/PrivacyService.swift:11:8: failed to build module 'TCPrivacy' from its module interface; the compiler that produced it, 'Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)'

I have XCode 12.5 
Swift version : 
Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)
Target: x86_64-apple-darwin20.3.0
