### ISSUE TITLE
A version that contains bitcode

### ISSUE THREAD

**Issue by clakhdhar** [TagCommander/pods#17]
Hello, 
There was a `latest-TCCore-Release-universal-Bitcode` and  `latest-TCSDK-Release-universal-Bitcode` but since the last update I could not find them anywhere.

When I archive the project with the latest pods I get this error:
`'/Users/clakhdhar/Library/Developer/Xcode/DerivedData/project-name/Build/Intermediates.noindex/ArchiveIntermediates/scheme-name/BuildProductsPath/ProductionRelease-iphoneos/XCFrameworkIntermediates/TCCore/TCCore.framework/TCCore' does not contain bitcode.`

Thanks.

**Comment by CommandersAct** [comment]
Did you use "latest-TCCore-Bitcode.podspec" to archive?
We transferred all releases in XCFramework removing the need of "Release", "Debug", "universal or not" builds.

**Comment by clakhdhar** [comment]
I could not find the link nor the name for the Bitcode version anywhere before.
But thanks to your response, everything works now.

Thanks a lot.
