### ISSUE TITLE
How to add [String?] array in addAdditionalParameter ? TCEvent

### ISSUE THREAD

**Issue by dleurs** [TagCommander/pods#21]
Hello, 

I would like to add [String?] inside my event, but it seems I can only add String or dictionnary :

- (void) addAdditionalParameter: (NSString *) key withValue: (NSString *) value ;
- (void) addAdditionalParameter: (NSString *) key forJsonDict: (NSDictionary *) json;

I can do :  

- "key": "string"
- "key": "[string1, string2]"
- "key": {"key": "value"}
- "key": {"key": ["string1", "string2"]}

I want to do :

- "key": ["string1", "string2"]

How can I achieve that ?

Thank you very much

```
//
//  TCEvent.h
//  TCServerSide
//
//  Created by Abdelhakim SAID on 20/01/2022.
//  Copyright © 2022 TagCommander. All rights reserved.
//

#ifndef events_TCEvent_h
#define events_TCEvent_h

#import <Foundation/Foundation.h>
#import "TCEventPropertiesNames.h"
#import <TCCore/TCUtils.h>
#import "ETCPayementMethod.h"
#import "ETCPurchaseStatus.h"

@class TCDynamicStore;

@interface TCEvent : NSObject

- (BOOL) verifyEvent;
- (NSMutableDictionary *) getJsonObject;
- (void) addAdditionalParameter: (NSString *) key withValue: (NSString *) value ;
- (void) addAdditionalParameter: (NSString *) key forJsonDict: (NSDictionary *) json;
- (void) addAdditionalParameter: (TCDynamicStore *) store;
- (TCDynamicStore *) getAdditionalParameters;
- (NSArray *) getItemListAsJson: (NSArray *) items;

@property (nonatomic, retain) NSString *name;
@property (nonatomic, retain) NSString *pageType;
@property (nonatomic, retain) NSString *pageName;

@end

#endif
```

My code 
```

        let customEvent:TCCustomEvent = TCCustomEvent(name: event.name)  (@interface TCCustomEvent : TCEvent)

       Working :

        event.additionalParameters?.forEach({ (key: String?, value: String?) in
            if let key = key, let value = value  {
                customEvent.addAdditionalParameter(key, withValue: value)
            }
        })

      Working :

        event.additionalJsonParameters?.forEach({ (key: String?, value: String?) in
            if let key = key, let value = value, let json = convertStringToDictionary(text: value)  {
                customEvent.addAdditionalParameter(key, forJsonDict: json)
            }
        })
        

BEGIN: HOW TO DO THIS PART ?

        event.additionalListParameters?.forEach({ (key: String?, value: [String?]?) in
            if let key = key, let value = value {
                customEvent.addAdditionalParameter(key, withValue: value)  => error
            }
        })
END
        
        
        customEvent.addAdditionalParameter("userData", forJsonDict: event.user.toMap())
        customEvent.name = event.eventName
        serverSide.execute(customEvent)
        completion(true)
}
    

func convertStringToDictionary(text: String) -> [String:AnyObject]? {
        if let data = text.data(using: .utf8) {
            do {
                let json = try JSONSerialization.jsonObject(with: data, options: .mutableContainers) as? [String:AnyObject]
                return json
            } catch {
                print("Something went wrong")
            }
        }
        return nil
    }
```

**Comment by dleurs** [comment]
With

```
        event.additionalListParameters?.forEach({ (key: String?, value: [String?]?) in
            if let key = key, let value = value {
                let data = try? JSONEncoder().encode(value)
                customEvent.addAdditionalParameter(key, withValue: data?.base64EncodedString())
            }
        })
```

If I want to pass: 
-  "test3": ["hello"],
I get with Charles Proxy (on iOS simulator) : 
- "test3":"WyJoZWxsbyJd",

**Comment by dleurs** [comment]
With 
```
        event.additionalListParameters?.forEach({ (key: String?, value: [String?]?) in
            if let key = key, let value = value, let json = convertStringToList(array: value)  {
                customEvent.addAdditionalParameter(key, withValue: json)
            }
        })
```

and 
```
    func convertStringToList(array: [String?]) -> String? {
        do {
            let data =  try JSONSerialization.data(withJSONObject:array, options: .prettyPrinted)
            return NSString(data: data, encoding: String.Encoding.utf8.rawValue) as! String
        } catch {
            print(error.localizedDescription)
        }
        return nil
    }
```
It stills add a string


<img width="391" alt="image" src="https://user-images.githubusercontent.com/58068925/206404858-b1836c76-bfcb-40c3-bf63-3d61f935b659.png">

**Comment by CommandersAct** [comment]
Hello @dleurs, 
Thank you for reaching out, we will be supporting other data types for additional Properties including Array values in the next release. 

++

**Comment by dleurs** [comment]
Thank you for your answer ! Do you have in mind a date for this release, approximately ?

It is the same for Android ? We are using Flutter with bridge in pigeon

**Comment by CommandersAct** [comment]
It should arrive soon ! 
Next week mostly.
And yes, support for other types is coming for the Android SDK also.

**Comment by CommandersAct** [comment]
Should now be possible with the latest versions.
Could you please test and tell us if it's working for you in swift?

**Comment by dleurs** [comment]
Is there a documentation on the new version ? 
To switch to addAdditionalParameter to addAdditionalProperty ?

**Comment by CommandersAct** [comment]
Yes, you should check the V5 documentation for that : 
https://github.com/CommandersAct/iOSV5/tree/master/TCServerSide#customising-events

**Comment by dleurs** [comment]
It seems addAdditionalProperty with withArrayValue is missing from the doc / link

**Comment by CommandersAct** [comment]
Thanks for pointing that, i can confirm that the method do exists in the latest frameworks, 
Documentation will be updated soon

**Comment by dleurs** [comment]
```addAdditionalProperty with withArrayValue``` seems to work on iOS 👍, I will continue working around it. Thank you !

Two questions : 
1. I was thinking about doing a documentation for implementing CommandersAct on Flutter with pigeon. Di you know where I can do it ?
2. Array not yet implemented on Android right ?

**Comment by CommandersAct** [comment]
1. We are currently working on a flutter wrapper, not sure what more you would require for pigeon tho, all mandatory public functions should be documented in github throughout all modules.
2. it wasn't released due to a mistake on our end, it should be working now.

**Comment by dleurs** [comment]
Thank you, it is working, iOS and Android, with inside the array String or Map

"items": [{"key1": "value1"}, "world"] working :)
