### ISSUE TITLE
tvOS / watchOS compatibility

### ISSUE THREAD

**Issue by defagos** [TagCommander/pods#4]
Hi,

We are currently adding tvOS support to our applications (we use `TCCore` and `TCSDK`), but I did not find any TagCommander tvOS binaries.

Do tvOS binaries already exist? If yes, could you please publish them?

If not, would it be possible to add tvOS support to your SDKs, for those for which this makes sense? I guess `TCCore` and `TCSDK` would be obvious candidates, but I have no experience with your other frameworks.

For information, there are different approaches to build tvOS binaries. The simplest one is to use a [single target to build all binaries](https://davedelong.com/blog/2018/11/15/building-a-crossplatform-framework):

- Clear the framework target base SDK.
Set `SUPPORTED_PLATFORMS = iphoneos iphonesimulator appletvos appletvsimulator`
- Set `TARGETED_DEVICE_FAMILY = 1,2,3`
- Set the deployment target for tvOS (your framework supports iOS 9, you should therefore be able to support tvOS 9 without any additional work).

Provided the source code does not reference APIs not available for some platform (which is quite likely for an analytics SDK), the code should be able to compile without additional work.

We are not considering any watchOS app at the moment, but I have the intuition that adding watchOS support would be quite straightforward in your case, in which case the target should be setup as follows:

- Clear the framework target base SDK.
Set `SUPPORTED_PLATFORMS = iphoneos iphonesimulator watchos watchsimulator appletvos appletvsimulator`
- Set `TARGETED_DEVICE_FAMILY = 1,2,3,4`
- Set the deployment target for tvOS (your framework supports iOS 9, you should therefore be able to support tvOS 9 without any additional work).
- Set the deployment target for watchOS in a similar way.

I am happy to help if needed. Feel free to get in touch.

Thanks in advance.

Best regards.

**Comment by CommandersAct** [comment]
Hello !
Sorry for the late reply, I had too much subjects at the same time.
And I wanted to check a bit before (but I couldn't).
What I can tell is that I'm right now not sure how to do that, we checked but 3 years ago and we need to make a new study on the subject.

I can start checking and working on it in two weeks and I'll get back to you if I find something that I don't understand :)

**Comment by defagos** [comment]
Thanks in advance for the work!
