### ISSUE TITLE
Replace `UIWebView` with `WKWebView` to comply with Apple's latest guidelines

### ISSUE THREAD

**Issue by marcelkalveram** [TagCommander/pods#5]
As per Apple's App Store guidelines, _Apple will stop accepting submissions of apps that use UIWebView APIs_. 

> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

When I search `TCCore.Framework` for occurrences of `UIWebView`, I get this:

```
$ grep -r "UIWebView" . 
Binary file ./TCCore matches
```

Looking into the file, I see some occurrences of `UIWebView`:

```
@_OBJC_CLASS_$_UIWebView
```

Would it be possible to replace `UIWebView` with `WKWebView` to comply with Apple's latest guidelines. Are you planning to release a Pods update that includes this change?

Thanks a lot in advance for looking into this!

**Comment by CommandersAct** [comment]
Hello !
Yes it has been put inside the planning.
We'll come back to you when the dev is over.

**Comment by CommandersAct** [comment]
Hello ! A new version has been pushed for this issue and to remove call to CLLocation.

**Comment by marcelkalveram** [comment]
@TagCommander awesome, thanks a lot!
