### ISSUE TITLE
ipatool failed with an exception (Non-fat file) when exporting TCCore

### ISSUE THREAD

**Issue by marcelkalveram** [TagCommander/pods#6]
Hello, I ran into the following error when exporting our iOS app.

We've included the latest `TCCore` (4.5.2) and `TCSDK` (4.4.1) from the `Release-universal` folder in our app. Both frameworks are **Bitcode-enabled**. So is our app.

The app works fine in debug mode, and the build works fine as well. But when exporting the app using the following command, we get an error. 

Apparently, something is wrong with the architecture and/or Bitcode. I'm not an iOS expert, but I think the error message **Non-fat file** is where to start investigating.

I also ran a few `lipo` commands on the frameworks to verify that they include all the architectures (armv7), and I've double-checked if they contain the Bitcode-enabled ones. I'm not sure what else I can do to debug this and narrow down the issue, so I'm posting this here.

I can't tell if it is app-specific, or if it's a general problem with the library. I'll try to create an isolated test case, but this may take another day or two.

Anyway, here's the debug output. If you need more, I can post the whole log, but I think these are the relevant pieces.

```
xcodebuild -exportArchive -archivePath ".../app.xcarchive" -exportPath "./exportPath" -exportOptionsPlist "./export_options.plist"
```

**The error message:**

```
error: exportArchive: ipatool failed with an exception: #<CmdSpec::NonZeroExcitException: Command exited with pid 8319 exit 1:
```

**More debugging output:**

```
/Applications/Xcode.app/Contents/Developer/usr/bin/bitcode-build-tool -v -t 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin --sdk 
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk -o /.../thinned-out/armv7/Payload/AppFile/Frameworks/TCCore.framework/TCCore --generate-dsym 
/.../thinned-out/armv7/Payload/.../Frameworks/TCCore.framework/TCCore.dSYM --strip-swift-symbols /.../thinned-in/armv7/Payload/AppFile/Frameworks/TCCore.framework/TCCore

Stdout:
Debug: SDK path: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk

Debug: PATH: ['/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin', '/Applications/Xcode.app/Contents/Developer/usr/bin']
Debug: Using: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo
MachoInfo: cd /
    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo" "-info" 
"/.../thinned-in/armv7/Payload/AppFile/Frameworks/TCCore.framework/TCCore"

-= Output =-
Non-fat file: /.../thinned-in/armv7/Payload/AppFile/Frameworks/TCCore.framework/TCCore is architecture: armv7
Exited with 0
...
```

**Comment by CommandersAct** [comment]
Hello !
Can you tell me which XCode version is used to build? We had a similar issue when client was building with a slightly older version than the SDK was.
Or maybe you updated XCode and we haven't yet, since I saw a new one was available.

**Comment by marcelkalveram** [comment]
@TagCommander thanks for the quick reply. We're building/exporting with xCode 10.1

It didn't occur to me, but yes, maybe we have to update to xCode 10.2 or 10.3?

**Comment by CommandersAct** [comment]
Yes we had the same issues not long ago with another client when using 10.2 on our side and 10.1 on the client side.
We updated in 10.3 which was supposed to solve this, seems not :(

**Comment by marcelkalveram** [comment]
Ok, we'll try to upgrade to 10.3 and see if the export issue still happens... Thanks for letting us know.

**Comment by CommandersAct** [comment]
Did it work? :)

**Comment by marcelkalveram** [comment]
As far as I remember, it resolved the issue, yes! Thanks again. Feel free to close this.
