### ISSUE TITLE
No IDFA version

### ISSUE THREAD

**Issue by celian-m** [TagCommander/pods#7]
HEllo,

Can you provide the pods name for the noIDFA variant? This is mentioned into the Readme but I can't find the pod itself.

Thanks

**Comment by CommandersAct** [comment]
https://raw.githubusercontent.com/TagCommander/pods/master/TCCore/latest-TCCore-Release-universal-Bitcode-noIDFA.podspec

https://raw.githubusercontent.com/TagCommander/pods/master/TCSDK/latest-TCSDK-Release-universal-Bitcode-noIDFA.podspec

They should be right at the origin of each modules :)

**Comment by celian-m** [comment]
It works Thanks!
