### ISSUE TITLE
Consent internal API for Privacy not visible

### ISSUE THREAD

**Issue by florentmorin** [TagCommander/pods#9]
Hello,

I want to use Consent internal API for Privacy, as explained in README file. But it's not visible. So I can't use it.

Thanks.

**Comment by CommandersAct** [comment]
Hello !
Are you sure you're using the latest version ?
We updated the header in one of the latest version because it was indeed missing before.

**Comment by florentmorin** [comment]
Sorry, it comes with `TCPrivacyAPI` and not `TCMobilePrivacy`. My fault.
